name: apply-trailing-reverse-patch
on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Apply trailing-reverse patch (in-function)
        run: |
          python - <<'PY'
          import re, pathlib, textwrap

          p = pathlib.Path("stargate_all_in_one.py")
          s = p.read_text(encoding="utf-8")

          changed = False

          # 0) 헬퍼 보강: _as_bool / trailing_enabled_from_cfg 없으면 주입
          if "def trailing_enabled_from_cfg(" not in s:
            inject = textwrap.dedent("""
            # === GPT PATCH HELPER: BEGIN ===
            def _as_bool(v, default=True):
                if v is None: return default
                if isinstance(v, bool): return v
                return str(v).strip().lower() in ("1","true","yes","y","on")

            def trailing_enabled_from_cfg(cfg):
                try:
                    if isinstance(cfg, dict):
                        if "enable_trailing" in cfg:
                            return _as_bool(cfg.get("enable_trailing"), True)
                        if "trailing_enabled" in cfg:
                            return _as_bool(cfg.get("trailing_enabled"), True)
                        t = cfg.get("trailing") or {}
                        if isinstance(t, dict) and "enabled" in t:
                            return _as_bool(t.get("enabled"), True)
                    return True
                except Exception:
                    return True
            # === GPT PATCH HELPER: END ===
            """).strip()+"\n\n"
            # import 아래에 삽입
            m = re.search(r"(?s)^(from .*?\\n|import .*?\\n)+", s)
            pos = m.end() if m else 0
            s = s[:pos] + inject + s[pos:]
            changed = True

          # 1) 맨 아래 fallback 라인 제거 (있으면)
          new_s, n = re.subn(
            r"\\n#\\s*GPT PATCH: fallback definition\\s*\\nreverse_on_opposite\\s*=\\s*\\(not\\s*trailing_enabled_from_cfg\\(globals\\(\\)\\.get\\('cfg',\\s*\\{\\}\\)\\)\\)\\s*\\n\\s*$",
            "\n",
            s
          )
          if n > 0:
            s = new_s
            changed = True

          # 2) 기존 reverse_on_opposite 대입은 모두 표준식으로 교체
          new_s, n = re.subn(
            r"(?m)^(\s*)reverse_on_opposite\s*=\s*.*$",
            r"\1reverse_on_opposite = (not trailing_enabled_from_cfg(locals().get('cfg', locals().get('settings', {}))))  # GPT PATCH",
            s
          )
          if n > 0:
            s = new_s
            changed = True

          # 3) /webhook(또는 유사) 함수 내부에 없으면 주입
          #    우선순위: @app.route('/webhook'...) -> def .*webhook.* -> def .*process.*signal.*
          patterns = [
            r"(?s)(@app\.route\(\s*['\"]/webhook['\"].*?\)\s*def\s+\w+\s*\(.*?\):\s*\n)",
            r"(?s)(def\s+\w*webhook\w*\s*\(.*?\):\s*\n)",
            r"(?s)(def\s+\w*process\w*signal\w*\s*\(.*?\):\s*\n)",
          ]

          def ensure_inside_function(src):
            for pat in patterns:
              m = re.search(pat, src)
              if m:
                indent = "    "
                insert_at = m.end()
                insert_line = indent + "reverse_on_opposite = (not trailing_enabled_from_cfg(locals().get('cfg', locals().get('settings', {}))))  # GPT PATCH: trailing OFF => reverse\n"
                # 이미 같은 줄이 함수 안에 있으면 중복 삽입 금지
                body_end = src.find("\ndef ", insert_at)
                seg = src[insert_at: body_end if body_end!=-1 else None]
                if "reverse_on_opposite = (not trailing_enabled_from_cfg" not in seg:
                  return src[:insert_at] + insert_line + src[insert_at:], True
                return src, False
            return src, False

          s, inj = ensure_inside_function(s)
          if inj:
            changed = True

          if changed:
            p.write_text(s, encoding="utf-8")
            print("PATCH APPLIED")
          else:
            print("No changes needed.")
          PY

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: patch/trailing-reverse-in-function
          commit-message: "server: set reverse_on_opposite inside webhook; remove fallback"
          title: "patch: 전환 조건을 웹훅 함수 내부에 설정 + fallback 제거"
          body: |
            - reverse_on_opposite를 /webhook(또는 신호 처리) 함수 **내부**에서 설정하도록 주입
            - 맨 아래 fallback 전역 라인 제거
            - 표준식: `reverse_on_opposite = (not trailing_enabled_from_cfg(locals().get('cfg', locals().get('settings', {}))))`
